---
name: Molecule CI
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: ansible_collections/kraus/pihole_automation

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] yamllint ansible-lint

      - name: print working directory
        run: pwd
        working-directory: ansible_collections/kraus/pihole_automation

      - name: Run Molecule tests.
        working-directory: ansible_collections/kraus/pihole_automation
        run: |
          pwd
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        working-directory: extensions
