---
name: Molecule CI
on:
  push:
    branches:
      - main

env:
  COLLECTION_PATH_PREFIX: ansible_collections/kraus/pihole_automation

jobs:
  test:
    name: Molecule tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: $COLLECTION_PATH_PREFIX

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] yamllint ansible-lint

      - name: Run Molecule tests.
        working-directory: ${{ env.COLLECTION_PATH_PREFIX }}/extensions
        run: |
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
